### ISSUE TITLE
unused imports in generated files

### ISSUE THREAD

**Issue by pivotal-anova** [maxbrunsfeld/counterfeiter#23] opened 2015-10-23 16:37 UTC
The fake seems to just copy all the import statements from the real file. We have a member of a value object in the real file that required an import, but which is not used anywhere in the fake. So we can't build after generating a fake for one of these files because the fake has an unused import we have to remove manually.

**Comment by tjarratt** [comment] 2018-01-30 09:07
Closing since I'm not sure I can actually reproduce this issue.

**Comment by tjarratt** [comment] 2018-01-30 09:08
Please re-open if you can help out by providing some reproduction steps or example code 😄

**Closed by tjarratt** 2018-01-30 09:07 UTC
