### ISSUE TITLE
Invalid import path on Windows

### ISSUE THREAD

**Issue by daniellavoie** [maxbrunsfeld/counterfeiter#79] opened 2018-01-14 22:04 UTC
I am unable to run counterfeiter on Windows. I tryed the same command on MacOS and I'm getting no error.

```
counterfeiter-test> counterfeiter services/io_services.go IoService
format.Node internal error (5:2: invalid import path: "github.com\\xcomponent\\counterfeiter-test\\services")
```

I tried running from a vanilla project with a single interface and I'm getting the same result. Any additional information could help you out ?

**Comment by tjarratt** [comment] 2018-01-29 13:22
Hey @daniellavoie sorry sorry for the long delay. I'm downloading a Windows VM image right now so that I can try this out.

**Comment by tjarratt** [comment] 2018-01-29 15:17
@daniellavoie I've just pushed a commit to github this afternoon that (on my virtual machine at least)  I can no longer reproduce. I'd be really curious to hear if running counterfeiter works on your machine if you run `go get -u github.com/maxbrunsfeld/counterfeiter` to update the binary.

**Comment by tjarratt** [comment] 2018-01-31 15:27
Phew. What a journey the past two days were. I wasn't entirely aware of it (because the amount of maintenance necessary to support counterfeiter has been fairly minimal), but apparently counterfeiter never had proper support for Windows. I'm fairly certain that certain bugs about path separators have been present for years.

The good news now is that counterfeiter now supports windows - and we now have our suite of tests running on [Appveyor](https://ci.appveyor.com) to verify that the build does not break in the future.

I'm going to close this out for now, but please re-open if you find any new issues @daniellavoie.

**Closed by tjarratt** 2018-01-31 15:27 UTC
Labels: bug, possibly-fixed ?
