### ISSUE TITLE
On Windows: `is not on GOPATH` error when running counterfeiter

### ISSUE THREAD

**Issue by saintbrendan** [maxbrunsfeld/counterfeiter#78] opened 2017-09-17 00:13 UTC
We invoked `scripts/test.sh` on a Windows 10 64-bit machine. 
```
scripts/test.sh

Generating fakes used by tests...

Path 'C:\Users\saint\go\src\github.com\maxbrunsfeld\counterfeiter\arguments' is not on GOPATH
Path 'C:\Users\saint\AppData\Local\Temp\symlinked_fixtures' is not on GOPATH
exit status 1
```
Our GOPATH:
```
echo %GOPATH%
C:\Users\saint\go
```
We believe that error is triggered on [this line](https://github.com/maxbrunsfeld/counterfeiter/blob/07943b8ac43d8bb3b5bb536b6540c866ba082808/locator/locator.go#L171), which mistakenly splits the GOPATH on `:`, not realizing that in Windows, the `:` is part of the path (e.g `C:\`) and not necessarily a separator.

We are using `go` 1.8:
```
go version
go version go1.8 windows/amd64
```

**Comment by saintbrendan** [comment] 2017-09-17 22:14
It looks like this specific problem can be solved by splitting on `os.PathListSeparator ` instead of on `':'`.

**Comment by tjarratt** [comment] 2017-09-20 20:08
It warms my heart that people using windows to write golang want to use counterfeiter. Thanks for taking the time to write up this beautiful description, and finding the source of the problem @saintbrendan  -- I really appreciate it.

I applied the fix you suggested in `7f6ceee8bbe9189968c960e3593724a953b39151`. Unfortunately I don't have access to a windows machine right now - any chance you'd be willing to check and see if the tests run (and pass ???) on Windows ?

**Comment by enchobelezirev** [comment] 2017-10-26 07:44
Hello,
When I tried to use it, I came to the following error: format.Node internal error (5:2: invalid import path: "github.com\\SAP\\cf-mta-plugin\\clients\\restclient") In my code, there is no import path with the following signature(\\).

**Comment by tjarratt** [comment] 2017-10-26 08:47
@enchobelezirev Very Interesting. I don't think I'll be able to debug that very well, since that sounds really specific to your project. If you think you can create a reproducible test case for that, I'd be more than happy to either contribute a fix, or help you in submitting a PR and getting it merged in a timely fashion.

I'm also not entirely convinced that is related to this issue. Were you trying to run `./scripts/test.sh` on a windows machine ? Could you walk me through some of the steps you took that resulted in that error being printed ?

**Comment by tjarratt** [comment] 2018-01-30 09:04
It looks like I was mistaken before. The error @enchobelezirev encountered is actually valid - there is some more discussion over in issue https://github.com/maxbrunsfeld/counterfeiter/issues/79.

I believe this to be fixed on master - at least, I can no longer reproduce this in a windows vm I'm using. Going forward, I'm going to invest a bit this week in setting up CI for windows so that these issues are discovered automatically and not by the community. 😬 

For now, I'd like to close this issue out, since I believe the original issue to be resolved. Please re-open this issue if I'm in error.

**Closed by tjarratt** 2018-01-30 09:04 UTC
