### ISSUE TITLE
import cycle when writing to the same package

### ISSUE THREAD

**Issue by cryptix** [maxbrunsfeld/counterfeiter#15] opened 2015-02-20 10:01 UTC
when writing the counterfeit to the same package, the source package is still imported and used in the generated code leading to `import cycle not allowed` errors.

```go
package cycle

type Data string

//go:generate counterfeiter -o tester.go . Tester
type Tester interface {
	Test() Data
}
```

```
[cryptix@higgs ~/go/src/github.com/cryptix/exp/cycle:master] go generate
Wrote `FakeTester` to `tester.go`
[cryptix@higgs ~/go/src/github.com/cryptix/exp/cycle:master] go test                            
can't load package: import cycle not allowed
package github.com/cryptix/exp/cycle
	imports github.com/cryptix/exp/cycle
import cycle not allowed
package github.com/cryptix/exp/cycle
	imports github.com/cryptix/exp/cycle
[cryptix@higgs ~/go/src/github.com/cryptix/exp/cycle:master] 
```

**Comment by maxbrunsfeld** [comment] 2015-02-23 18:35
I think this is a dupe of #8.

**Closed by maxbrunsfeld** 2015-02-23 18:35 UTC
